FROM golang:1.23-alpine

WORKDIR /app

COPY . .

# Downloading docker
RUN apk update
RUN apk upgrade
RUN apk add --no-cache docker-cli

# Building image that tork will use
# RUN docker build -t gcc-compiler .

# Downloading Go modules and building it
RUN go mod download
RUN go build -o /server main.go

#EXPOSE 8000

ENTRYPOINT ["/server", "run", "standalone"]
