FROM golang:1.23.0-alpine3.19

WORKDIR /app

COPY main.go .
COPY go.mod go.sum ./
COPY ./handler ./handler
COPY config.toml .

# Downloading Go modules and building it
RUN go mod download
RUN go build -o /server main.go

# RUN apk update
# RUN apk upgrade
# RUN apk add --no-cache podman

EXPOSE 80

ENTRYPOINT /server migration || /server run standalone

# For debugging
# CMD ["/bin/sh"]
