[coordinator.api]
endpoints.health = true
endpoints.jobs = false
endpoints.tasks = false
endpoints.nodes = false
endpoints.queues = false
endpoints.metrics = false

# cors middleware
[middleware.web.cors]
enabled = true
origins = "*" # TODO: RESTRICT ORIGINS
methods = "POST"
credentials = false
headers = "*"
